### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by gmarik** [StephaneBour/sense-chrome#10]
## Problem
Followed the instructions and got Chrome error:
<img width="722" alt="screen shot 2017-12-15 at 11 06 31 am" src="https://user-images.githubusercontent.com/31292/34050247-3c11e54c-e188-11e7-97e4-d85ded49eedb.png">

## Workaround
Deleting `_config.yml` allowed the Chrome to load the plugin…

**Comment by StephaneBour** [comment]
Ok, thanks for the preview ;-)

**Comment by StephaneBour** [comment]
@gmarik it's done.

**Comment by gmarik** [comment]
@StephaneBour thank you for taking the lead on Sense plugin!
