### ISSUE TITLE
load failed

### ISSUE THREAD

**Issue by hrdxwandg** [StephaneBour/sense-chrome#20]
when i load the extension in chrome, it crashed as follows:File

~/Documents/StudySoftware/sense
Manifest file is missing or unreadable
Could not load manifest.

how can i modify? thanks

**Comment by StephaneBour** [comment]
Hi @hrdxwandg,

Can you send me a screenshoot, and your chrome version, which I'm trying to reproduce?

Thank you

**Comment by hrdxwandg** [comment]
@StephaneBour 

thanks for your reply.

<img width="510" alt="wx20180612-161158 2x" src="https://user-images.githubusercontent.com/2166948/41278058-7ceb7f96-6e5b-11e8-9b37-64064c98cb7a.png">

the version of chrome is:     Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by StephaneBour** [comment]
Do you have a manifest.json file in your project ?

I test my [manifest.json](https://github.com/StephaneBour/sense-chrome/blob/master/manifest.json) with https://manifest-validator.appspot.com/, and i have a success.

**Comment by hrdxwandg** [comment]
@StephaneBour 

I am very sorry. i get the wrong clone from the readme.
I get clone from https://github.com/elastic/sense

Now I reclone the repo from https://github.com/StephaneBour/sense-chrome.git, and get right. thank you very much

**Comment by StephaneBour** [comment]
No problem ;-)
