### ISSUE TITLE
Input chinese is not supported

### ISSUE THREAD

**Issue by smallmenu** [StephaneBour/sense-chrome#22]
Hi,  It's just like the dev-tool in lastest Kibana，Because I use ES 2.4.X，Thanks for this tool。

in my test, I find  Input Chinese in the input textarea is not supported

How about fix this?

Google Chrome 70.0

**Comment by StephaneBour** [comment]
Hi @smallmenu, can you send me a sample of data ?

index name and one post for tests.

Thank you

**Comment by KasureSp** [comment]
![image](https://user-images.githubusercontent.com/31438946/53631065-95357380-3c4c-11e9-98cd-83a6de7d59ec.png)
Like this, I want to input Chinese about  "data.itemTitle" query. When I entered Chinese, nothing happened, no text appeared.

It does not seem to support Chinese input.

**Comment by amoibean** [comment]
Hi, @smallmenu, @KasureSp,

copy-paste works for me.
