### ISSUE TITLE
Deprecated field name

### ISSUE THREAD

**Issue by compwiztobe** [StephaneBour/sense-chrome#23]
https://github.com/StephaneBour/sense-chrome/blob/b8d044410d4564f7c5beec9d1af4a82aeba8a33e/kb/query.js#L73 is deprecated, it's now `minimum_should_match`.

https://discuss.elastic.co/t/q-re-deprecated-field-minimum-number-should-match/77343/2

**Comment by StephaneBour** [comment]
Hello @compwiztobe ,

It's fixed by 1d5e65c .

Thanks for the report.

**Comment by compwiztobe** [comment]
Thanks for maintaining this very useful tool!
