### ISSUE TITLE
requests need to provide Content-Type in ES6

### ISSUE THREAD

**Issue by jmlucjav** [StephaneBour/sense-chrome#3]
or you get:

{
   "error": "Content-Type header [application/x-www-form-urlencoded; charset=UTF-8] is not supported",
   "status": 406
}

**Comment by StephaneBour** [comment]
Hello,

Can you give more details to reproduce this bug?

**Comment by jmlucjav** [comment]
sure, just try this against ES6.0:

`GET  _search
{
   "query": {
      "match_all": {}
   }
}`

**Comment by StephaneBour** [comment]
Yes, but how to choose es6 on chrome?

**Comment by StephaneBour** [comment]
Ok, ES6.0 for you is ElasticSearch 6.0 and for me it's EcmaScript 6 (2015) ;-)

**Comment by jmlucjav** [comment]
oh yes....I meant Elasticsearch lol

**Comment by StephaneBour** [comment]
@jmlucjav : i have try with docker and ElasticSearch 6.0. I have fix on 40a764e . Can you try directely on this branch and confirm it's good ? I merge when you confirm. Thank.

**Comment by jmlucjav** [comment]
works fine, thanks!
