### ISSUE TITLE
Why was it blacklisted?

### ISSUE THREAD

**Issue by gerrywastaken** [StephaneBour/sense-chrome#5]
Do you know why the original was blacklisted? Did you fork from the blacklisted version or elsewhere?

**Comment by StephaneBour** [comment]
Hi @gerrywastaken , 

The problem comes from the permission to access all url, which is now contrary to the general conditions. However, it is essential to access all servers.

It's a fork since the blacklisted version.

I deleted all the parts that communicated with the outside (google analytics).

**Comment by gerrywastaken** [comment]
@StephaneBour Thanks for letting us know.
