### ISSUE TITLE
Error with _config.yml

### ISSUE THREAD

**Issue by maxxkrakoa** [StephaneBour/sense-chrome#8]
After the addition of `_config.yml` I now get the following error:

```
Cannot load extension with file or directory name _config.yml.
Filenames starting with "_" are reserved for use by the system.
```

**Comment by StephaneBour** [comment]
Oh. This file was added directly by github when I activated the github pages.

It is not useful to the project, you can delete it locally.

**Comment by StephaneBour** [comment]
I have completed the documentation for use directly online from sense.stephane.tech.

That's why there is the _config.yml file and the CNAME file.
